version: "3.8"

services:
  web:
    container_name: web
    image: als698/web:latest
    volumes:
      - web:/var/www/html # ./web/html:/var/www/html #local edit
      - db:/db
    ports:
      - "80:80"
    # environment:
      # IMPORT_DB: 1

volumes:
  web:
  db: