version: "3.8"

services:
  web:
    container_name: web
    image: als698/web:latest
    # build:
      # context: .
    volumes:
      - ./web/html:/var/www/html
    ports:
      - "80:8080"
    # environment:
      # IMPORT_DB: 1