version: "3.8"

services:
  web:
    container_name: web
    image: als698/web:latest
    # build:
      # context: .
    depends_on:
      - db
    volumes:
      - ./web:/var/www/html
    ports:
      - "80:8080"
    environment:
      FOO: bar
  db:
    image: mysql:8
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    cap_add:
      - SYS_NICE
  pma:
    container_name: pma
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "81:80"
    environment:
      PMA_HOST: db
      PMA_USER: app
      PMA_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app